### ISSUE TITLE
Date format doesn't follow locale

### ISSUE THREAD

**Issue by niezywa** [Knedme/Time-in-date-menu#1]
The extension displays the date in the month-day-year format as opposed to the one indicated by locale and used elsewhere in Gnome.

![Zrzut ekranu z 2022-08-22 00-54-14](https://user-images.githubusercontent.com/104802727/185816602-ec78046f-5d5e-4622-9710-990a69de80a5.png)

**Comment by Knedme** [comment]
fixed in version 2
