### ISSUE TITLE
[Enhancement] [Feature] Able to change between AM/PM & 24 hour format

### ISSUE THREAD

**Issue by 0Raik** [Knedme/Time-in-date-menu#4]
It always shows 24 hour format. Not everyone uses that format.
Thanks for your time and effort developing this extension. Nice day.

**Comment by Knedme** [comment]
I've just added this feature to the settings in the new extension version.

**Comment by 0Raik** [comment]
Thank you!!!

Been enjoying so far... until Gnome 45 dropped in Manjaro. :)

**Comment by Knedme** [comment]
GNOME 45 version of extension has been released today.
